// ============================================================
// StickerWorld — Catalogue des villes du monde
// Un sticker pour chaque ville. Données : nom, pays, continent.
// Le visuel du sticker est généré automatiquement (voir app.js).
// ============================================================

const CONTINENTS = [
    { id: "all",      label: "🌍 Toutes" },
    { id: "europe",   label: "🇪🇺 Europe" },
    { id: "africa",   label: "🌍 Afrique" },
    { id: "asia",     label: "🌏 Asie" },
    { id: "americas", label: "🌎 Amériques" },
    { id: "oceania",  label: "🦘 Océanie" },
];

// flag = emoji drapeau du pays (utilisé sur le sticker)
const CITIES = [
    // ---------- Europe ----------
    { name: "Paris",        country: "France",          flag: "🇫🇷", continent: "europe" },
    { name: "Lyon",         country: "France",          flag: "🇫🇷", continent: "europe" },
    { name: "Marseille",    country: "France",          flag: "🇫🇷", continent: "europe" },
    { name: "Bordeaux",     country: "France",          flag: "🇫🇷", continent: "europe" },
    { name: "Londres",      country: "Royaume-Uni",     flag: "🇬🇧", continent: "europe" },
    { name: "Édimbourg",    country: "Royaume-Uni",     flag: "🇬🇧", continent: "europe" },
    { name: "Berlin",       country: "Allemagne",       flag: "🇩🇪", continent: "europe" },
    { name: "Munich",       country: "Allemagne",       flag: "🇩🇪", continent: "europe" },
    { name: "Madrid",       country: "Espagne",         flag: "🇪🇸", continent: "europe" },
    { name: "Barcelone",    country: "Espagne",         flag: "🇪🇸", continent: "europe" },
    { name: "Séville",      country: "Espagne",         flag: "🇪🇸", continent: "europe" },
    { name: "Rome",         country: "Italie",          flag: "🇮🇹", continent: "europe" },
    { name: "Milan",        country: "Italie",          flag: "🇮🇹", continent: "europe" },
    { name: "Venise",       country: "Italie",          flag: "🇮🇹", continent: "europe" },
    { name: "Lisbonne",     country: "Portugal",        flag: "🇵🇹", continent: "europe" },
    { name: "Porto",        country: "Portugal",        flag: "🇵🇹", continent: "europe" },
    { name: "Amsterdam",    country: "Pays-Bas",        flag: "🇳🇱", continent: "europe" },
    { name: "Bruxelles",    country: "Belgique",        flag: "🇧🇪", continent: "europe" },
    { name: "Genève",       country: "Suisse",          flag: "🇨🇭", continent: "europe" },
    { name: "Zurich",       country: "Suisse",          flag: "🇨🇭", continent: "europe" },
    { name: "Vienne",       country: "Autriche",        flag: "🇦🇹", continent: "europe" },
    { name: "Prague",       country: "Tchéquie",        flag: "🇨🇿", continent: "europe" },
    { name: "Budapest",     country: "Hongrie",         flag: "🇭🇺", continent: "europe" },
    { name: "Varsovie",     country: "Pologne",         flag: "🇵🇱", continent: "europe" },
    { name: "Cracovie",     country: "Pologne",         flag: "🇵🇱", continent: "europe" },
    { name: "Stockholm",    country: "Suède",           flag: "🇸🇪", continent: "europe" },
    { name: "Copenhague",   country: "Danemark",        flag: "🇩🇰", continent: "europe" },
    { name: "Oslo",         country: "Norvège",         flag: "🇳🇴", continent: "europe" },
    { name: "Helsinki",     country: "Finlande",        flag: "🇫🇮", continent: "europe" },
    { name: "Dublin",       country: "Irlande",         flag: "🇮🇪", continent: "europe" },
    { name: "Athènes",      country: "Grèce",           flag: "🇬🇷", continent: "europe" },
    { name: "Istanbul",     country: "Turquie",         flag: "🇹🇷", continent: "europe" },
    { name: "Moscou",       country: "Russie",          flag: "🇷🇺", continent: "europe" },
    { name: "Saint-Pétersbourg", country: "Russie",     flag: "🇷🇺", continent: "europe" },
    { name: "Reykjavik",    country: "Islande",         flag: "🇮🇸", continent: "europe" },

    // ---------- Afrique ----------
    { name: "Dakar",        country: "Sénégal",         flag: "🇸🇳", continent: "africa" },
    { name: "Abidjan",      country: "Côte d'Ivoire",   flag: "🇨🇮", continent: "africa" },
    { name: "Lagos",        country: "Nigéria",         flag: "🇳🇬", continent: "africa" },
    { name: "Accra",        country: "Ghana",           flag: "🇬🇭", continent: "africa" },
    { name: "Le Caire",     country: "Égypte",          flag: "🇪🇬", continent: "africa" },
    { name: "Marrakech",    country: "Maroc",           flag: "🇲🇦", continent: "africa" },
    { name: "Casablanca",   country: "Maroc",           flag: "🇲🇦", continent: "africa" },
    { name: "Tunis",        country: "Tunisie",         flag: "🇹🇳", continent: "africa" },
    { name: "Alger",        country: "Algérie",         flag: "🇩🇿", continent: "africa" },
    { name: "Nairobi",      country: "Kenya",           flag: "🇰🇪", continent: "africa" },
    { name: "Addis-Abeba",  country: "Éthiopie",        flag: "🇪🇹", continent: "africa" },
    { name: "Le Cap",       country: "Afrique du Sud",  flag: "🇿🇦", continent: "africa" },
    { name: "Johannesburg", country: "Afrique du Sud",  flag: "🇿🇦", continent: "africa" },
    { name: "Kinshasa",     country: "RD Congo",        flag: "🇨🇩", continent: "africa" },
    { name: "Bamako",       country: "Mali",            flag: "🇲🇱", continent: "africa" },
    { name: "Yaoundé",      country: "Cameroun",        flag: "🇨🇲", continent: "africa" },
    { name: "Kigali",       country: "Rwanda",          flag: "🇷🇼", continent: "africa" },

    // ---------- Asie ----------
    { name: "Tokyo",        country: "Japon",           flag: "🇯🇵", continent: "asia" },
    { name: "Kyoto",        country: "Japon",           flag: "🇯🇵", continent: "asia" },
    { name: "Osaka",        country: "Japon",           flag: "🇯🇵", continent: "asia" },
    { name: "Séoul",        country: "Corée du Sud",    flag: "🇰🇷", continent: "asia" },
    { name: "Pékin",        country: "Chine",           flag: "🇨🇳", continent: "asia" },
    { name: "Shanghai",     country: "Chine",           flag: "🇨🇳", continent: "asia" },
    { name: "Hong Kong",    country: "Chine",           flag: "🇭🇰", continent: "asia" },
    { name: "Bangkok",      country: "Thaïlande",       flag: "🇹🇭", continent: "asia" },
    { name: "Singapour",    country: "Singapour",       flag: "🇸🇬", continent: "asia" },
    { name: "Bali",         country: "Indonésie",       flag: "🇮🇩", continent: "asia" },
    { name: "Jakarta",      country: "Indonésie",       flag: "🇮🇩", continent: "asia" },
    { name: "Hô Chi Minh",  country: "Viêt Nam",        flag: "🇻🇳", continent: "asia" },
    { name: "Hanoï",        country: "Viêt Nam",        flag: "🇻🇳", continent: "asia" },
    { name: "New Delhi",    country: "Inde",            flag: "🇮🇳", continent: "asia" },
    { name: "Mumbai",       country: "Inde",            flag: "🇮🇳", continent: "asia" },
    { name: "Jaipur",       country: "Inde",            flag: "🇮🇳", continent: "asia" },
    { name: "Dubaï",        country: "Émirats A. U.",   flag: "🇦🇪", continent: "asia" },
    { name: "Doha",         country: "Qatar",           flag: "🇶🇦", continent: "asia" },
    { name: "Tel Aviv",     country: "Israël",          flag: "🇮🇱", continent: "asia" },
    { name: "Manille",      country: "Philippines",     flag: "🇵🇭", continent: "asia" },
    { name: "Katmandou",    country: "Népal",           flag: "🇳🇵", continent: "asia" },

    // ---------- Amériques ----------
    { name: "New York",     country: "États-Unis",      flag: "🇺🇸", continent: "americas" },
    { name: "Los Angeles",  country: "États-Unis",      flag: "🇺🇸", continent: "americas" },
    { name: "San Francisco",country: "États-Unis",      flag: "🇺🇸", continent: "americas" },
    { name: "Chicago",      country: "États-Unis",      flag: "🇺🇸", continent: "americas" },
    { name: "Miami",        country: "États-Unis",      flag: "🇺🇸", continent: "americas" },
    { name: "Toronto",      country: "Canada",          flag: "🇨🇦", continent: "americas" },
    { name: "Montréal",     country: "Canada",          flag: "🇨🇦", continent: "americas" },
    { name: "Vancouver",    country: "Canada",          flag: "🇨🇦", continent: "americas" },
    { name: "Mexico",       country: "Mexique",         flag: "🇲🇽", continent: "americas" },
    { name: "Cancún",       country: "Mexique",         flag: "🇲🇽", continent: "americas" },
    { name: "La Havane",    country: "Cuba",            flag: "🇨🇺", continent: "americas" },
    { name: "Rio de Janeiro",country: "Brésil",         flag: "🇧🇷", continent: "americas" },
    { name: "São Paulo",    country: "Brésil",          flag: "🇧🇷", continent: "americas" },
    { name: "Buenos Aires", country: "Argentine",       flag: "🇦🇷", continent: "americas" },
    { name: "Santiago",     country: "Chili",           flag: "🇨🇱", continent: "americas" },
    { name: "Lima",         country: "Pérou",           flag: "🇵🇪", continent: "americas" },
    { name: "Cusco",        country: "Pérou",           flag: "🇵🇪", continent: "americas" },
    { name: "Bogotá",       country: "Colombie",        flag: "🇨🇴", continent: "americas" },
    { name: "Carthagène",   country: "Colombie",        flag: "🇨🇴", continent: "americas" },

    // ---------- Océanie ----------
    { name: "Sydney",       country: "Australie",       flag: "🇦🇺", continent: "oceania" },
    { name: "Melbourne",    country: "Australie",       flag: "🇦🇺", continent: "oceania" },
    { name: "Brisbane",     country: "Australie",       flag: "🇦🇺", continent: "oceania" },
    { name: "Auckland",     country: "Nouvelle-Zélande",flag: "🇳🇿", continent: "oceania" },
    { name: "Wellington",   country: "Nouvelle-Zélande",flag: "🇳🇿", continent: "oceania" },
    { name: "Suva",         country: "Fidji",           flag: "🇫🇯", continent: "oceania" },
    { name: "Papeete",      country: "Polynésie fr.",   flag: "🇵🇫", continent: "oceania" },
];

const PRICE = 4.90; // prix unitaire en euros
